export * as ReportGenTool from "./report-gen"

import { ToolFailure } from "@opencode-ai/llm"
import { Effect, Layer, Schema } from "effect"
import { makeLocationNode } from "../effect/app-node"
import { ToolRegistry } from "./registry"
import { Tool } from "./tool"
import { Tools } from "./tools"
import { FSUtil } from "../fs-util"
import path from "path"

export const name = "report_gen"

export const Input = Schema.Struct({
  title: Schema.String.annotate({ description: "Engagement report title (e.g., 'Pentest Report - target.com')" }),
  target: Schema.String.annotate({ description: "Target domain/IP/scope description" }),
  findings: Schema.String.annotate({
    description: "All findings in structured format. Include severity, description, evidence, and remediation for each finding.",
  }),
  output_path: Schema.String.pipe(Schema.optional).annotate({
    description: "Output file path for the report. Defaults to ./pentest-report.md",
  }),
  format: Schema.String.pipe(Schema.optional).annotate({
    description: "Report format: 'markdown' (default), 'html'.",
  }),
})

const Output = Schema.Struct({
  output: Schema.String,
  path: Schema.String,
})

type Output = typeof Output.Type

const layer = Layer.effectDiscard(
  Effect.gen(function* () {
    const tools = yield* Tools.Service
    const fs = yield* FSUtil.Service

    yield* tools
      .register({
        [name]: Tool.make({
          description: `Generate professional penetration testing engagement reports. Compiles findings into a structured report with executive summary, vulnerability details, CVSS scoring, evidence, and remediation recommendations. Outputs markdown or HTML format.`,
          input: Input,
          output: Output,
          toModelOutput: ({ output }) => [{ type: "text", text: output.output }],
          execute: (input) =>
            Effect.gen(function* () {
              const date = new Date().toISOString().split("T")[0]
              const outputPath = input.output_path ?? "./pentest-report.md"

              const report = `# ${input.title}

**Date:** ${date}
**Target:** ${input.target}
**Classification:** CONFIDENTIAL

---

## Executive Summary

This report presents the findings of an authorized penetration testing engagement against ${input.target}. The assessment was conducted using industry-standard methodologies (PTES, OWASP) to identify security vulnerabilities and assess the overall security posture.

---

## Scope

- **Target:** ${input.target}
- **Assessment Date:** ${date}
- **Methodology:** PTES (Penetration Testing Execution Standard)
- **Tools Used:** nmap, nuclei, sqlmap, gobuster, subfinder, theHarvester, and custom scripts

---

## Findings Summary

| Severity | Count |
|----------|-------|
| Critical | - |
| High     | - |
| Medium   | - |
| Low      | - |
| Info     | - |

---

## Detailed Findings

${input.findings}

---

## Remediation Priorities

1. Address all CRITICAL findings immediately
2. Remediate HIGH findings within 30 days
3. Address MEDIUM findings within 90 days
4. Plan LOW findings for next development cycle

---

## Disclaimer

This assessment was performed under authorized engagement terms. Findings and techniques described are for the purpose of improving security posture. All testing was conducted within the agreed scope and rules of engagement.

---

*Report generated by OpenCode Red Team Agent*
`

              const htmlReport = input.format === "html"
                ? `<!DOCTYPE html>
<html><head><title>${input.title}</title>
<style>
body { font-family: 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; background: #0d1117; color: #c9d1d9; }
h1 { color: #ff4444; border-bottom: 2px solid #ff4444; padding-bottom: 0.5rem; }
h2 { color: #58a6ff; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
th, td { border: 1px solid #30363d; padding: 0.5rem 1rem; text-align: left; }
th { background: #161b22; }
.critical { color: #ff4444; font-weight: bold; }
.high { color: #ff8800; font-weight: bold; }
.medium { color: #ffcc00; }
.low { color: #58a6ff; }
pre { background: #161b22; padding: 1rem; border-radius: 6px; overflow-x: auto; }
</style></head><body>
${report.replace(/^# /gm, '<h1>').replace(/^## /gm, '<h2>').replace(/\n/g, '<br>')}
</body></html>`
                : report

              const finalContent = input.format === "html" ? htmlReport : report
              const finalPath = input.format === "html" ? outputPath.replace(/\.md$/, ".html") : outputPath

              yield* Effect.promise(async () => {
                const file = Bun.file(finalPath)
                await Bun.write(file, finalContent)
              })

              return {
                output: `✅ Report generated successfully: ${finalPath}\n\nReport contains: Executive Summary, Scope, Findings Summary, Detailed Findings, Remediation Priorities.`,
                path: finalPath,
              }
            }).pipe(Effect.mapError(() => new ToolFailure({ message: "Report generation failed" }))),
        }),
      })
      .pipe(Effect.orDie)
  }),
)

export const node = makeLocationNode({
  name: "tool/report-gen",
  layer,
  deps: [ToolRegistry.node, FSUtil.node],
})
